import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the counter
const initialCounterState = {
    counter: 0,
    showCounter: true,
};

// Create a slice of the Redux store for the counter
const counterSlice = createSlice({
    name: "counter", // Name of the slice
    initialState: initialCounterState, // Initial state of the counter
    reducers: {
        // Reducer function to increment the counter
        increment(state) {
            state.counter++;
        },
        // Reducer function to decrement the counter
        decrement(state) {
            state.counter--;
        },
        // Reducer function to increase the counter by a specific value
        increase(state, action) {
            state.counter = state.counter + action.payload;
        },
        // Reducer function to toggle the visibility of the counter
        toggle(state) {
            state.showCounter = !state.showCounter;
        },
    },
});

// Export the actions generated by the counter slice
export const counterActions = counterSlice.actions;

// Export the reducer function generated by the counter slice
export default counterSlice.reducer;
